// core domain  types for job entity.

// categorized ATS keywords generated by AI for a specific job.
// recruiters can use to configure ATS filtering rules.

export type ATSKeywords = {
  hardSkills: string[];
  softSkills: string[];
  qualifications: string[];
  experience: string[];
};

// the output returned by the AI generation service.
// contain the job description and categorized ATS keywords.

export type GeneratedJob = {
  title: string;
  seniority: string;
  industry: string;
  jobDescription: string;
  atsKeywords: ATSKeywords;
};

// a job record as it stored and retrieved from the Azure Table Storage.

export type JobRecord = {
  rowKey: string;
  title: string;
  seniority: string;
  industry: string;
  description: string;
  requirements: string;
  atsKeywordsJson: string;
};

// input required from the recruiter to trigger job generation.

export type CreateJobInput = {
  title: string;
  seniority: string;
  industry: string;
  responsibilities: string;
};
