export type QuestionType = "mcq" | "truefalse" | "shortanswer";

export interface QuizQuestion {
  id: string;
  question: string;
  type: QuestionType;
  idealAnswer: string; //used for scoring
  options: string[];
  explanation: string; // for recruiters use
}

export type GenerateQuizInput = {
  jobId: string;
  topic?: string;
  questionCount: number;
  jobTitle?: string;
  jobDescription?: string;
};

export type QuizRecord = {
  rowKey: string;
  jobId: string;
  topic: string;
  allQuestionsJson: string; //all the questions generated by the AI
  selectedQuestionsJson: string; //questions that the recruiter selected to proceed with
  questionCount: number;
  createdAt: string;
};
